glory_user_home:
    path:   /user
    defaults: { _controller: GloryUserBundle:Default:index }

# security #
glory_user_login:
    path: /login
    defaults: { _controller:GloryUserBundle:Security:login }
glory_user_check:
    path: /login/check
    methods: [POST]
glory_user_logout:
    path: /logout

# register #
glory_user_register:
    path: /register
    defaults: { _controller: GloryUserBundle:Register:register }
glory_user_register_success:
    path: /register/success
    defaults: { _controller: GloryUserBundle:Register:success }
fos_user_registration_confirmed:
    path: /register/success
    defaults: { _controller: GloryUserBundle:Register:confirmed }
glory_user_register_check_email:
    path: /register/check/email
    defaults: { _controller: GloryUserBundle:Register:checkEmail }

glory_user_reset:
    path: /reset
    defaults: { _controller: GloryUserBundle:Reset:password }

# profile #
glory_user_my:
    path: /my
    defaults: { _controller: GloryUserBundle:My:index }
glory_user_profile:
    path: /my/profile
    defaults: { _controller: GloryUserBundle:Profile:index }
glory_user_profile_edit:
    path: /my/profile/edit
    defaults: { _controller: GloryUserBundle:Profile:edit }
glory_user_profile_username:
    path: /my/profile/username
    defaults: 
        _controller: GloryUserBundle:Profile:edit
        field: username

glory_user_password:
    path: /my/profile/password
    defaults: { _controller: GloryUserBundle:Profile:password }
glory_user_profile_password:
    path: /my/profile/password
    defaults: { _controller: GloryUserBundle:Profile:password }
glory_user_profile_avatar:
    path: /my/profile/avatar
    defaults: { _controller: GloryUserBundle:Profile:avatar }

# admin security #
glory_user_admin_login:
    path:   /admin/login
    defaults: { _controller: GloryUserBundle:Admin\Security:login }
glory_user_admin_check:
    path:   /admin/check
glory_user_admin_logout:
    path:   /admin/logout

# admin group #
glory_user_group:
    path: /admin/group
    defaults: { _controller: GloryUserBundle:Admin\Group:list }
glory_user_group_create:
    path: /admin/group/create
    defaults: { _controller: GloryUserBundle:Admin\Group:create }
glory_user_group_show:
    path: /admin/group/{id}
    defaults: { _controller: GloryUserBundle:Admin\Group:show }
glory_user_group_edit:
    path: /admin/group/{id}/edit
    defaults: { _controller: GloryUserBundle:Admin\Group:edit }
glory_user_group_delete:
    path: /admin/group/{id}/delete
    defaults: { _controller: GloryUserBundle:Admin\Group:delete }

# admin user #
glory_user_manage:
    path: /admin/user
    defaults: { _controller: GloryUserBundle:Admin\User:list }
glory_user_manage_create:
    path: /admin/user/create
    defaults: { _controller: GloryUserBundle:Admin\User:create }
glory_user_manage_show:
    path: /admin/user/{id}
    defaults: { _controller: GloryUserBundle:Admin\User:show }
glory_user_manage_edit:
    path: /admin/user/{id}/edit
    defaults: { _controller: GloryUserBundle:Admin\User:edit }
glory_user_manage_delete:
    path: /admin/user/{id}/delete
    defaults: { _controller: GloryUserBundle:Admin\User:delete }
