services:
    glory.user.listener.registration:
        class: Glory\Bundle\UserBundle\EventListener\RegistrationListener
        arguments: [@service_container]
        tags: 
            - { name: kernel.event_subscriber }
